export type StoreItemKind = "chatbot" | "api" | "image" | "video" | "audio" | "code";

export type StoreItem = {
  id: string;
  brand: string;
  product: string;
  detail: string;
  kind: StoreItemKind;
  badge?: string;
  duration: string;
  priceVnd: number;
  originalVnd?: number;
  stock: "in" | "low" | "preorder";
  warranty: string;
  notes?: string;
};

export const aiStoreCatalog: ReadonlyArray<StoreItem> = [
  {
    id: "chatgpt-plus-1m",
    brand: "OpenAI",
    product: "ChatGPT Plus",
    detail: "GPT-5, Sora 2, Advanced Voice, Codex CLI",
    kind: "chatbot",
    badge: "HOT",
    duration: "1 tháng",
    priceVnd: 380000,
    originalVnd: 520000,
    stock: "in",
    warranty: "Bảo hành 1-1 trong suốt thời hạn",
    notes: "Đăng nhập bằng tài khoản chính chủ user, an toàn 100%",
  },
  {
    id: "chatgpt-pro-1m",
    brand: "OpenAI",
    product: "ChatGPT Pro",
    detail: "Pro Mode · o3 · Operator · Sora unlimited",
    kind: "chatbot",
    duration: "1 tháng",
    priceVnd: 4200000,
    stock: "low",
    warranty: "Bảo hành 1-1",
    notes: "Tài khoản share giảm 60%, liên hệ Telegram",
  },
  {
    id: "claude-pro-1m",
    brand: "Anthropic",
    product: "Claude Pro",
    detail: "Claude Opus 4.7, Projects, Artifacts",
    kind: "chatbot",
    badge: "BEST",
    duration: "1 tháng",
    priceVnd: 380000,
    originalVnd: 520000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "claude-max-1m",
    brand: "Anthropic",
    product: "Claude Max 5x",
    detail: "Claude Code, 5x usage, Opus access cao hơn",
    kind: "chatbot",
    duration: "1 tháng",
    priceVnd: 2400000,
    stock: "low",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "openai-api-codex",
    brand: "OpenAI",
    product: "Codex API key",
    detail: "Cho Cursor / Cline / Codex CLI · cap $200",
    kind: "api",
    badge: "NEW",
    duration: "1 tháng",
    priceVnd: 1800000,
    stock: "in",
    warranty: "Refill khi hết quota",
    notes: "Stable, không bị OpenAI khoá",
  },
  {
    id: "anthropic-api",
    brand: "Anthropic",
    product: "Anthropic API key",
    detail: "Claude Sonnet 4.6 · Opus 4.7 · cap $100",
    kind: "api",
    duration: "1 tháng",
    priceVnd: 980000,
    stock: "in",
    warranty: "Refill khi hết quota",
  },
  {
    id: "cursor-pro-1m",
    brand: "Cursor",
    product: "Cursor Pro",
    detail: "500 fast premium requests/tháng",
    kind: "code",
    duration: "1 tháng",
    priceVnd: 320000,
    originalVnd: 480000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "github-copilot-1m",
    brand: "GitHub",
    product: "Copilot Pro",
    detail: "Copilot Chat · Code completion · agent mode",
    kind: "code",
    duration: "1 tháng",
    priceVnd: 180000,
    originalVnd: 250000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "midjourney-basic",
    brand: "Midjourney",
    product: "Midjourney Basic",
    detail: "200 ảnh/tháng · Discord + web",
    kind: "image",
    duration: "1 tháng",
    priceVnd: 280000,
    originalVnd: 400000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "midjourney-standard",
    brand: "Midjourney",
    product: "Midjourney Standard",
    detail: "Unlimited relax · 15 fast hour",
    kind: "image",
    duration: "1 tháng",
    priceVnd: 580000,
    originalVnd: 720000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "dreamina-pro",
    brand: "ByteDance",
    product: "Dreamina Pro",
    detail: "Image + Video AI, không watermark",
    kind: "video",
    badge: "VIET",
    duration: "1 tháng",
    priceVnd: 320000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "runway-standard",
    brand: "Runway",
    product: "Runway Standard",
    detail: "625 credits · Gen-4 · Aleph editor",
    kind: "video",
    duration: "1 tháng",
    priceVnd: 480000,
    originalVnd: 620000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "kling-pro-1m",
    brand: "Kuaishou",
    product: "Kling AI Pro",
    detail: "Video 10s · Kling 2.5 Turbo · 660 credits",
    kind: "video",
    duration: "1 tháng",
    priceVnd: 380000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "suno-pro-1m",
    brand: "Suno",
    product: "Suno Pro",
    detail: "v5 · 2500 credits · clone giọng",
    kind: "audio",
    duration: "1 tháng",
    priceVnd: 280000,
    originalVnd: 360000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "elevenlabs-creator",
    brand: "ElevenLabs",
    product: "ElevenLabs Creator",
    detail: "100K char · clone giọng · 192kbps",
    kind: "audio",
    duration: "1 tháng",
    priceVnd: 380000,
    stock: "in",
    warranty: "Bảo hành 1-1",
  },
  {
    id: "fal-credits-50",
    brand: "FAL.AI",
    product: "FAL Credits $50",
    detail: "Dùng cho FLUX, Veo, Sora, Kling, Seedream",
    kind: "api",
    duration: "Vĩnh viễn",
    priceVnd: 1450000,
    stock: "in",
    warranty: "Refill ngay khi hết",
    notes: "API key riêng, dùng được trên AI Playground",
  },
];
